CREATE DATABASE admission;
USE admission;
CREATE TABLE student(admNo INT PRIMARY KEY, studName VARCHAR(30) NOT NULL, course VARCHAR(30) NOT NULL, dept VARCHAR(30) NOT NULL);
CREATE TABLE student(admNo INT PRIMARY KEY, studName VARCHAR(30) NOT NULL, course VARCHAR(30) NOT NULL, dept VARCHAR(30) NOT NULL);